name: Validate Memory Core JSON
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          set -e
          for f in memory_core.json ui.json hardware.json projects.json output_pipeline.json references.json catalog.json; do
            echo "Checking $f"
            jq . "$f" >/dev/null
          done
          echo "✅ All JSON validated."
